lfscanning/scaffold

config.py
createreports.py
datatypes.py
importscan.py
runners.py

Adds support for import SPDX files and generating reports via https://github.com/swinslow/spdxLicenseManager
Signed-off-by: Steve Winslow <swinslow@gmail.com>

Add support for spdxLicenseManager

---

datefuncs.py
emailing.py
scaffold.py

Add command to print email with report links

---

config.py
datatypes.py
delivering.py
findings.py
instancesfile.py
runners.py
scaffold.py
tickets.py

Handle instances and JIRA ticket filings

---

datatypes.py
metrics.py
metricsfile.py
scaffold.py

Add and extend metrics

---

config.py
datatypes.py
findings.py
parsespdx.py

Add per-subproject license policies

---

config.py
datatypes.py
zipcode.py

Add ability to remove specific directories

---

scaffold.py
transfer.py

Add command to transfer to new Fossology server

---

config.py
findings.py

Minor fixes for config and findings

---

findings.py

Add end-of-path matching for findings

---

.gitignore
config.py
datatypes.py
manualws.py
runagents.py
runners.py
scaffold.py
uploadcode.py
uploadws.py
ws/wsagent.py
ws/wsapi.py
ws/wscfg.py

Add uploading to WhiteSource

---

config.py
docs/config.md

Make the webserver required even when the use SCP option is false

---

config.py

Throw exceptions on invalid configurations

---

docs/config.md
docs/findings-sample.yaml
docs/matches-sample.json

Add finding.yaml and matches.json formats to documentation

---

docs/config.md
docs/matches-sample.json

Completes the documentation for the matches configuration file

Update documentation for matches remove action

---

docs/usage.md

Add documentation for SPDX git repo creation

---

docs/usage.md
scaffold.py

Add lockfile to prevent concurrent access to the same month

---

config.py
datatypes.py
docs/config-template.json
docs/config.md
runagents.py
tests/testfossology.py
tests/testresources/scaffoldhome/2023-07/config.json
uploadcode.py

Adds an upload timeout and the jobspec to the configuration file.

Add FOSSOlogy configuration parameters to config file

---

getcode.py
tests/testfossology.py

Handle Git repos with no commits

---

config.py
datatypes.py
docs/config-template.json
docs/config.md
tests/testfossology.py
tests/testresources/scaffoldhome/2023-07/config.json
uploadcode.py

Remove timeout for file uploads

---

runagents.py

Fixes an issue where the project name in the scaffold config file is all lowercase and the github project name is mixed case

Ignore case when looking for prior uploads

---

getcode.py
tests/testgetcode.py

This should improve the performance of the git clone

Change Git clone to do a shallow copy

---

runagents.py

Up the number of months back to look for previous scans

---

getcode.py
tests/testgetcode.py

Always add the code_repos in get_code

---

requirements.txt
trivyagent.py
uploadspdx.py

Fixes #81 
Fixes #80 
Fixes #79

Fix issues found in initial Trivy deployment

---

spdx/xlsx.py
tests/testspdxutil.py

Improve check for None licenses

---

config.py
datatypes.py
docs/config.md
docs/unit-tests.md
tests/testtrivy.py
trivyagent.py

Make the Trivy executable path configurable

---

spdx/spdxutil.py
tests/testresources/test-materialx-conf.json
tests/testspdxutil.py
trivyagent.py

Prevent exception when project licenses are not valid SPDX expressions

---

spdx/xlsx.py

Use license_concluded in SPDX XLSX spreadsheet

---

README.md
config.py
datatypes.py
docs/config.md
docs/unit-tests.md
docs/usage.md
spdx/spdxutil.py
tests/testtrivy.py
trivyagent.py

Add Parlay to enrich Trivy SBOM data

---

README.md
spdx/spdxutil.py
tests/testresources/materialx-2024-08-21.json
tests/testspdxutil.py

Change algorithm for project licenses

---

spdx/spdxutil.py
tests/testresources/MaterialX-2024-08-21-trivy-spdx.json
tests/testspdxutil.py

Remove duplicate packages from Trivy results

---

spdx/spdxutil.py
tests/testspdxutil.py

Add version and supplier to Trivy file pkgs

---

README.md
docs/usage.md
manualsbom.py
sbomagent.py
scaffold.py
spdx/spdxutil.py
spdx/xlsx.py
tests/testsbom.py
tests/testspdxutil.py

Rename trivy command to sbom

---

manualsbom.py
sbomagent.py
scaffold.py
tests/testresources/scaffoldhome/2023-07/config.json
tests/testsbom.py

Support project level SBOM command

---

README.md
config.py
datatypes.py
sbomagent.py
tests/testsbom.py
uploadspdx.py

Add cdsbom enrichment to SBOM path

---

manualsbom.py
sbomagent.py
spdx/spdxutil.py
tests/testsbom.py
tests/testspdxutil.py

This is what was causing the parlay output file parsing errors.
Fixes #150 
Fixes #149

Various fixes including fixing the licenses strings in the SBOMs

---

spdx/spdxutil.py
tests/testspdxutil.py

Check for LicenseRef-'s when validating license strings

---

spdx/spdxutil.py

Fix extracted license text issues

---

requirements.txt
sbomagent.py
uploadspdx.py

Fixes #114 
Also partially addresses the missing extracted license infos.
This PR also updates the version of the SPDX Python tools dependency.

Zip large SBOMs before uploading to GitHub

---

emailing.py
spdx/spdxutil.py

Update printlinks to only use directory for SBOMs

---

sbomagent.py
spdx/spdxutil.py
tests/testresources/testfossology.spdx
tests/testresources/testsbom.json
tests/testsbom.py

Implement merged SBOM

---

spdx/spdxutil.py

Also adds licenseref text for any missing license refs

Fix license strings that contain NONE and NOASSERTION
